-- MySQL Script generated by MySQL Workbench
-- Sun Oct 29 18:14:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pap` DEFAULT CHARACTER SET utf8 ;
USE `pap` ;

-- -----------------------------------------------------
-- Table `pap`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pap`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(245) NOT NULL,
  `email` VARCHAR(245) NOT NULL,
  `password` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pap`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pap`.`perfil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(245) NOT NULL,
  `imageUrl` VARCHAR(245),
  `genero` VARCHAR(45),
  `descricao` VARCHAR(245),
  `data_nascimento` VARCHAR(45) NOT NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_table1_Usuario_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_table1_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `pap`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pap`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pap`.`posts` (
  `idposts` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  `foto` VARCHAR(245) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idposts`),
  INDEX `fk_posts_perfil1_idx` (`perfil_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_perfil1`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `pap`.`perfil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
